scores = {
    "Q1": { 
        "a": {  # Problem-solving / analytical thinking
            "Frontend Developer": 8,
            "Backend Developer": 10,
            "Full-Stack Developer": 10,
            "Mobile App Developer": 9,
            "DevOps Engineer": 7,
            "Data Analyst": 8,
            "Data Scientist": 10,
            "Machine Learning Engineer": 10,
            "Cybersecurity Specialist": 9,
            "Cloud Engineer": 7,
            "UI/UX Designer": 5,
            "Product Manager": 7,
            "Project Manager": 7
        },
        "b": {  # Communication
            "Frontend Developer": 7,
            "Backend Developer": 6,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 6,
            "DevOps Engineer": 6,
            "Data Analyst": 7,
            "Data Scientist": 7,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 5,
            "Cloud Engineer": 6,
            "UI/UX Designer": 9,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "c": {  # Creativity and innovation
            "Frontend Developer": 9,
            "Backend Developer": 6,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 8,
            "DevOps Engineer": 5,
            "Data Analyst": 5,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 5,
            "UI/UX Designer": 10,
            "Product Manager": 9,
            "Project Manager": 6
        },
        "d": {  # Leadership
            "Frontend Developer": 4,
            "Backend Developer": 4,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 4,
            "DevOps Engineer": 7,
            "Data Analyst": 5,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 6,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "e": {  # Adaptability
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 9,
            "Mobile App Developer": 8,
            "DevOps Engineer": 10,
            "Data Analyst": 7,
            "Data Scientist": 8,
            "Machine Learning Engineer": 9,
            "Cybersecurity Specialist": 9,
            "Cloud Engineer": 10,
            "UI/UX Designer": 7,
            "Product Manager": 8,
            "Project Manager": 8
        },
        "f": {  # Something else (neutral)
            "Frontend Developer":5,
            "Backend Developer":5,
            "Full-Stack Developer":5,
            "Mobile App Developer":5,
            "DevOps Engineer":5,
            "Data Analyst":5,
            "Data Scientist":5,
            "Machine Learning Engineer":5,
            "Cybersecurity Specialist":5,
            "Cloud Engineer":5,
            "UI/UX Designer":5,
            "Product Manager":5,
            "Project Manager":5
        }
    },
    # Q2: Which of the following appeals to you the most? 
    "Q2":{
        "a": { # Coding
            "Frontend Developer": 10,
            "Backend Developer": 10,
            "Full-Stack Developer": 10,
            "Mobile App Developer": 9,
            "DevOps Engineer": 6,
            "Data Analyst": 2,
            "Data Scientist": 2,
            "Machine Learning Engineer": 3,
            "Cybersecurity Specialist": 2,
            "Cloud Engineer": 7,
            "UI/UX Designer": 4,
            "Product Manager": 3,
            "Project Manager": 3
        },
        "b":{ # Designing
            "Frontend Developer": 8,
            "Backend Developer": 2,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 8,
            "DevOps Engineer": 1,
            "Data Analyst": 2,
            "Data Scientist": 1,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 10,
            "Product Manager": 5,
            "Project Manager": 2
        },
        "c": { #Analyzing data
            "Frontend Developer": 3,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 3,
            "DevOps Engineer": 5,
            "Data Analyst": 10,
            "Data Scientist": 10,
            "Machine Learning Engineer": 9,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 5,
            "UI/UX Designer": 3,
            "Product Manager": 6,
            "Project Manager": 6
        },
        "d": { # Ensuring systems run smoothly
            "Frontend Developer": 3,
            "Backend Developer": 7,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 4,
            "DevOps Engineer": 8,
            "Data Analyst": 4,
            "Data Scientist": 5,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 10,
            "Cloud Engineer": 8,
            "UI/UX Designer": 2,
            "Product Manager": 5,
            "Project Manager": 5
        },
        "e": { # Leading projects
            "Frontend Developer": 4,
            "Backend Developer": 4,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 4,
            "DevOps Engineer": 7,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 5,
            "Product Manager": 9,
            "Project Manager": 10
        }
    },
    # Q3: If you had to take a class right now, which would you pick?
    "Q3": {
        "a": {  # Psychology
            "Frontend Developer": 2,
            "Backend Developer": 1,
            "Full-Stack Developer": 2,
            "Mobile App Developer": 2,
            "DevOps Engineer": 1,
            "Data Analyst": 2,
            "Data Scientist": 1,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 5,
            "Product Manager": 4,
            "Project Manager": 3
        },
        "b": {  # Maths
            "Frontend Developer": 2,
            "Backend Developer": 3,
            "Full-Stack Developer": 3,
            "Mobile App Developer": 2,
            "DevOps Engineer": 2,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 3,
            "Cloud Engineer": 2,
            "UI/UX Designer": 1,
            "Product Manager": 2,
            "Project Manager": 2
        },
        "c": {  # Marketing
            "Frontend Developer": 2,
            "Backend Developer": 1,
            "Full-Stack Developer": 2,
            "Mobile App Developer": 2,
            "DevOps Engineer": 1,
            "Data Analyst": 3,
            "Data Scientist": 2,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 3,
            "Product Manager": 5,
            "Project Manager": 3
        },
        "d": {  # Art
            "Frontend Developer": 3,
            "Backend Developer": 1,
            "Full-Stack Developer": 2,
            "Mobile App Developer": 3,
            "DevOps Engineer": 1,
            "Data Analyst": 1,
            "Data Scientist": 1,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 5,
            "Product Manager": 2,
            "Project Manager": 1
        },
        "e": {  # Management
            "Frontend Developer": 1,
            "Backend Developer": 1,
            "Full-Stack Developer": 1,
            "Mobile App Developer": 1,
            "DevOps Engineer": 3,
            "Data Analyst": 2,
            "Data Scientist": 2,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 2,
            "Cloud Engineer": 3,
            "UI/UX Designer": 1,
            "Product Manager": 5,
            "Project Manager": 5
        },
        "f": { # Computing
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 5,
            "DevOps Engineer": 5,
            "Data Analyst": 4,
            "Data Scientist": 4,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 4,
            "UI/UX Designer": 2,
            "Product Manager": 3,
            "Project Manager": 3
        }
    },
    # Q4: You're teaming up with a few friends to launch a small business. Which role do you think you'd contribute to the most?
    "Q4": {
        "a": {  # Keeping the project organized, handling potential risks, and keeping everyone updated
            "Frontend Developer": 3,
            "Backend Developer": 3,
            "Full-Stack Developer": 4,
            "Mobile App Developer": 3,
            "DevOps Engineer": 5,
            "Data Analyst": 4,
            "Data Scientist": 3,
            "Machine Learning Engineer": 3,
            "Cybersecurity Specialist": 5,
            "Cloud Engineer": 4,
            "UI/UX Designer": 3,
            "Product Manager": 9,
            "Project Manager": 10
        },
        "b": {  # Creating the company’s visual identity and design elements
            "Frontend Developer": 6,
            "Backend Developer": 2,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 6,
            "DevOps Engineer": 1,
            "Data Analyst": 2,
            "Data Scientist": 1,
            "Machine Learning Engineer": 1,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 10,
            "Product Manager": 4,
            "Project Manager": 2
        },
        "c": {  # Finding ways the business can grow and improve
            "Frontend Developer": 4,
            "Backend Developer": 4,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 5,
            "DevOps Engineer": 4,
            "Data Analyst": 8,
            "Data Scientist": 9,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 5,
            "UI/UX Designer": 5,
            "Product Manager": 9,
            "Project Manager": 8
        },
        "d": {  # Designing and launching campaigns to increase brand visibility
            "Frontend Developer": 4,
            "Backend Developer": 1,
            "Full-Stack Developer": 2,
            "Mobile App Developer": 3,
            "DevOps Engineer": 1,
            "Data Analyst": 3,
            "Data Scientist": 2,
            "Machine Learning Engineer": 2,
            "Cybersecurity Specialist": 1,
            "Cloud Engineer": 1,
            "UI/UX Designer": 6,
            "Product Manager": 8,
            "Project Manager": 7
        },
        "e": { # Taking care of all the behind-the-scenes technology
            "Frontend Developer": 7,
            "Backend Developer": 10,
            "Full-Stack Developer": 9,
            "Mobile App Developer": 8,
            "DevOps Engineer": 8,
            "Data Analyst": 6,
            "Data Scientist": 7,
            "Machine Learning Engineer": 9,
            "Cybersecurity Specialist": 9,
            "Cloud Engineer": 8,
            "UI/UX Designer": 2,
            "Product Manager": 5,
            "Project Manager": 4
        },
        "f":{ # Understanding customers and making sure their needs are met
            "Frontend Developer": 6,
            "Backend Developer": 3,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 5,
            "DevOps Engineer": 2,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 3,
            "Cloud Engineer": 3,
            "UI/UX Designer": 8,
            "Product Manager": 10,
            "Project Manager": 8
        }
    },
    # Q5: When you work in a group, which role do you tend to take on?
    "Q5": {
        "a": {  # Leader
            "Frontend Developer": 4,
            "Backend Developer": 3,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 4,
            "DevOps Engineer": 6,
            "Data Analyst": 4,
            "Data Scientist": 4,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 5,
            "Cloud Engineer": 5,
            "UI/UX Designer": 6,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "b": {  # Organizer
            "Frontend Developer": 4,
            "Backend Developer": 4,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 4,
            "DevOps Engineer": 7,
            "Data Analyst": 5,
            "Data Scientist": 4,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 5,
            "Product Manager": 9,
            "Project Manager": 10
        },
        "c": {  # Idea generator
            "Frontend Developer": 7,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 7,
            "DevOps Engineer": 4,
            "Data Analyst": 5,
            "Data Scientist": 6,
            "Machine Learning Engineer": 7,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 5,
            "UI/UX Designer": 9,
            "Product Manager": 9,
            "Project Manager": 6
        },
        "d": {  # Listener
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 7,
            "DevOps Engineer": 5,
            "Data Analyst": 7,
            "Data Scientist": 6,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 5,
            "Cloud Engineer": 5,
            "UI/UX Designer": 8,
            "Product Manager": 8,
            "Project Manager": 9
        },
        "e": { # Other
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 5,
            "DevOps Engineer": 5,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 5,
            "Cloud Engineer": 5,
            "UI/UX Designer": 5,
            "Product Manager": 5,
            "Project Manager": 5
        }
    },
    # Q6: You're getting ready to launch a brand new fitness app. What matters most to you?
    "Q6": {
        "a": {  # That it's been thoroughly tested by potential users
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 7,
            "DevOps Engineer": 8,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 7,
            "Cloud Engineer": 7,
            "UI/UX Designer": 8,
            "Product Manager": 9,
            "Project Manager": 9
        },
        "b": {  # That the interface is intuitive and helps users stay motivated and engaged
            "Frontend Developer": 9,
            "Backend Developer": 4,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 9,
            "DevOps Engineer": 3,
            "Data Analyst": 4,
            "Data Scientist": 4,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 3,
            "Cloud Engineer": 3,
            "UI/UX Designer": 10,
            "Product Manager": 8,
            "Project Manager": 7
        },
        "c": {  # That development stays on schedule and within the planned budget
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 5,
            "DevOps Engineer": 7,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 4,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "d": {  # That the app runs smoothly without any glitches
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 8,
            "DevOps Engineer": 9,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 8,
            "Cloud Engineer": 8,
            "UI/UX Designer": 7,
            "Product Manager": 8,
            "Project Manager": 8
        },
        "e": { # That there's a strong marketing plan to reach the target audience
            "Frontend Developer": 4,
            "Backend Developer": 3,
            "Full-Stack Developer": 4,
            "Mobile App Developer": 4,
            "DevOps Engineer": 3,
            "Data Analyst": 4,
            "Data Scientist": 4,
            "Machine Learning Engineer": 4,
            "Cybersecurity Specialist": 3,
            "Cloud Engineer": 3,
            "UI/UX Designer": 5,
            "Product Manager": 10,
            "Project Manager": 9
        },
        "f": { # That the design is visually appealing and aligns with the brand identity
            "Frontend Developer": 8,
            "Backend Developer": 3,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 8,
            "DevOps Engineer": 3,
            "Data Analyst": 3,
            "Data Scientist": 3,
            "Machine Learning Engineer": 3,
            "Cybersecurity Specialist": 3,
            "Cloud Engineer": 3,
            "UI/UX Designer": 10,
            "Product Manager": 8,
            "Project Manager": 7
        },
        "g":{ # That it meets an unmet need in the current market
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 7,
            "DevOps Engineer": 5,
            "Data Analyst": 7,
            "Data Scientist": 7,
            "Machine Learning Engineer": 7,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 5,
            "UI/UX Designer": 5,
            "Product Manager": 10,
            "Project Manager": 8
        }
    },
    # Q7: How do you manage your time and prioritise tasks?
    "Q7": {
        "a": {  # I plan everything in detail and stick to my schedule.
            "Frontend Developer": 6,
            "Backend Developer": 6,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 6,
            "DevOps Engineer": 8,
            "Data Analyst": 7,
            "Data Scientist": 7,
            "Machine Learning Engineer": 7,
            "Cybersecurity Specialist": 7,
            "Cloud Engineer": 8,
            "UI/UX Designer": 6,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "b": {  # I start with tasks I really enjoy.
            "Frontend Developer": 7,
            "Backend Developer": 4,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 7,
            "DevOps Engineer": 4,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 4,
            "Cloud Engineer": 4,
            "UI/UX Designer": 8,
            "Product Manager": 4,
            "Project Manager": 4
        },
        "c": {  # I rely on deadlines and reminders to keep me on track.
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 7,
            "DevOps Engineer": 8,
            "Data Analyst": 9,
            "Data Scientist": 9,
            "Machine Learning Engineer": 8,
            "Cybersecurity Specialist": 8,
            "Cloud Engineer": 8,
            "UI/UX Designer": 6,
            "Product Manager": 8,
            "Project Manager": 9
        },
        "d": {  # I often work best under pressure, even if it means last-minute pushes
            "Frontend Developer": 6,
            "Backend Developer": 6,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 7,
            "DevOps Engineer": 7,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 6,
            "UI/UX Designer": 5,
            "Product Manager": 6,
            "Project Manager": 6
        },
        "e":{ # I combine a solid plan with flexibility when needed
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 9,
            "Mobile App Developer": 8,
            "DevOps Engineer": 9,
            "Data Analyst": 8,
            "Data Scientist": 8,
            "Machine Learning Engineer": 8,
            "Cybersecurity Specialist": 8,
            "Cloud Engineer": 9,
            "UI/UX Designer": 7,
            "Product Manager": 10,
            "Project Manager": 10
        }
    },
    # Q8: Which best describes how you like to work?
    "Q8":{
        "a":{ # I like working alone on focused tasks
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 8,
            "DevOps Engineer": 6,
            "Data Analyst": 9,
            "Data Scientist": 10,
            "Machine Learning Engineer": 10,
            "Cybersecurity Specialist": 9,
            "Cloud Engineer": 8,
            "UI/UX Designer": 5,
            "Product Manager": 3,
            "Project Manager": 2
        },
        "b":{ # I enjoy working with others as a team
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 6,
            "DevOps Engineer": 8,
            "Data Analyst": 7,
            "Data Scientist": 7,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 8,
            "UI/UX Designer": 9,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "c":{ # I like leading and organizing people
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 5,
            "DevOps Engineer": 8,
            "Data Analyst": 4,
            "Data Scientist": 4,
            "Machine Learning Engineer": 5,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 8,
            "UI/UX Designer": 7,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "d":{ # I enjoy learning and tackling new challenges
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 7,
            "DevOps Engineer": 9,
            "Data Analyst": 8,
            "Data Scientist": 10,
            "Machine Learning Engineer": 10,
            "Cybersecurity Specialist": 7,
            "Cloud Engineer": 9,
            "UI/UX Designer": 6,
            "Product Manager": 7,
            "Project Manager": 6
        }
    },
    # Q9: What best describes your long-term career vision?
    "Q9": {
        "a":{ # I want to become a top technical expert in my field
            "Frontend Developer": 8,
            "Backend Developer": 9,
            "Full-Stack Developer": 9,
            "Mobile App Developer": 8,
            "DevOps Engineer": 8,
            "Data Analyst": 7,
            "Data Scientist": 10,
            "Machine Learning Engineer": 10,
            "Cybersecurity Specialist": 10,
            "Cloud Engineer": 8,
            "UI/UX Designer": 4,
            "Product Manager": 5,
            "Project Manager": 5
        },
        "b":{ # I aim to take on leadership roles and guide teams or projects
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 5,
            "DevOps Engineer": 7,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 6,
            "Product Manager": 10,
            "Project Manager": 10
        },
        "c":{ # I value a stable job that supports a strong work-life balance
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 8,
            "DevOps Engineer": 6,
            "Data Analyst": 9,
            "Data Scientist": 7,
            "Machine Learning Engineer": 6,
            "Cybersecurity Specialist": 6,
            "Cloud Engineer": 7,
            "UI/UX Designer": 9,
            "Product Manager": 8,
            "Project Manager": 8
        },
        "d":{ # I strive to constantly innovate and embrace new challenges
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 7,
            "DevOps Engineer": 9,
            "Data Analyst": 6,
            "Data Scientist": 10,
            "Machine Learning Engineer": 10,
            "Cybersecurity Specialist": 8,
            "Cloud Engineer": 9,
            "UI/UX Designer": 8,
            "Product Manager": 8,
            "Project Manager": 7
        }
    },
    # Q10: I'm good at prioritising tasks when I'm working on multiple projects
    "Q10": {
        "a": {  # No, not at all
            "Frontend Developer": 10,
            "Backend Developer": 10,
            "Full-Stack Developer": 9,
            "Mobile App Developer": 9,
            "Data Analyst": 8,
            "Data Scientist": 8,
            "Machine Learning Engineer": 8,
            "UI/UX Designer": 7,
            "Cybersecurity Specialist": 7,
            "DevOps Engineer": 5,
            "Cloud Engineer": 5,
            "Product Manager": 1,
            "Project Manager": 1
        },
        "b": {  # I don't think so
            "Frontend Developer": 8,
            "Backend Developer": 8,
            "Full-Stack Developer": 7,
            "Mobile App Developer": 7,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "UI/UX Designer": 5,
            "Cybersecurity Specialist": 5,
            "DevOps Engineer": 3,
            "Cloud Engineer": 3,
            "Product Manager": 1,
            "Project Manager": 1
        },
        "c": {  # I'm unsure
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 5,
            "Mobile App Developer": 5,
            "Data Analyst": 5,
            "Data Scientist": 5,
            "Machine Learning Engineer": 5,
            "UI/UX Designer": 5,
            "Cybersecurity Specialist": 5,
            "DevOps Engineer": 5,
            "Cloud Engineer": 5,
            "Product Manager": 5,
            "Project Manager": 5
        },
        "d": {  # I think so
            "Frontend Developer": 5,
            "Backend Developer": 5,
            "Full-Stack Developer": 6,
            "Mobile App Developer": 5,
            "Data Analyst": 6,
            "Data Scientist": 6,
            "Machine Learning Engineer": 6,
            "UI/UX Designer": 5,
            "Cybersecurity Specialist": 7,
            "DevOps Engineer": 8,
            "Cloud Engineer": 8,
            "Product Manager": 9,
            "Project Manager": 9
        },
        "e": { # Definitely
            "Frontend Developer": 7,
            "Backend Developer": 7,
            "Full-Stack Developer": 8,
            "Mobile App Developer": 5,
            "Data Analyst": 8,
            "Data Scientist": 7,
            "Machine Learning Engineer": 7,
            "UI/UX Designer": 6,
            "Cybersecurity Specialist": 8,
            "DevOps Engineer": 10,
            "Cloud Engineer": 10,
            "Product Manager": 10,     
        }
    }
}